name: 流水线自动部署Vue项目到服务器

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: 拉取代码
        uses: actions/checkout@v5

      - name: 安装Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: 安装依赖
        run: npm ci

      - name: 打包Vue项目
        run: npm run build

      - name: 清理服务器目标目录
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # 每次上传文件前
          # 都会先删除目录下所有现有内容（包含隐藏文件），但不删除目录本身。
          script: |
            mkdir -p /www/xiyuewen/club
            find /www/xiyuewen/club -mindepth 1 -maxdepth 1 -exec rm -rf {} +

      - name: 上传dist到服务器
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist/*"
          target: "/www/xiyuewen/club"
          strip_components: 1
          overwrite: true

      - name: 检查并重载Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # -t 检查语法
          script: |
            sudo /usr/local/nginx/sbin/nginx -t
            sudo /usr/local/nginx/sbin/nginx -s reload
